import { approvalHooks } from './hooks/approvals';
import { deliveryHooks } from './hooks/delivery';
import { drawingHooks } from './hooks/drawings';
import { installationHooks, siteQcHooks } from './hooks/site';
import { productionOrderHooks } from './hooks/production';
import { variationHooks } from './hooks/variations';
import { baselineHooks } from './reports';
import type { ModuleDef } from './types';

/**
 * Every Phase 3 module collection. Each entry ties an app collection (NWContext state)
 * to its table, the columns projected from the record, how it reaches a project (scope),
 * the existing permission names that govern it, and any business-rule hooks.
 */
const num = (f: string) => (r: Record<string, unknown>) => (typeof r[f] === 'number' ? r[f] : Number(r[f]) || 0);

export const MODULES: ModuleDef[] = [
  // ---------------- Group A: drawings & documents ----------------
  {
    key: 'drawings',
    table: 'drawings',
    path: 'drawings',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'drawing_number' }, { col: 'status' }, { col: 'current_revision_id' }],
    scope: { kind: 'project' },
    perms: { view: 'drawings.view', create: 'drawings.upload', edit: ['drawings.upload', 'drawings.markup', 'drawings.create_production', 'drawings.approve'], delete: null },
    required: ['project_id', 'drawing_number'],
    hooks: drawingHooks,
  },
  {
    key: 'documents',
    table: 'documents',
    path: 'documents',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'status' }],
    scope: { kind: 'project' },
    perms: { view: 'projects.view', create: ['drawings.upload', 'projects.edit'], edit: ['drawings.upload', 'projects.edit'], delete: 'projects.edit' },
    required: ['project_id'],
  },

  // ---------------- Issues, tasks, approvals, variations ----------------
  {
    key: 'issues',
    table: 'issues',
    path: 'issues',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'work_item_id' }, { col: 'status' }, { col: 'priority' }, { col: 'assigned_to_id' }],
    scope: { kind: 'project' },
    perms: { view: 'issues.view', create: 'issues.create', edit: ['issues.assign', 'issues.resolve', 'issues.escalate'], delete: null },
    required: ['project_id', 'status'],
  },
  {
    key: 'tasks',
    table: 'tasks',
    path: 'tasks',
    idField: 'id',
    columns: [
      { col: 'project_id' },
      { col: 'work_package_id' },
      { col: 'work_item_id' },
      { col: 'status' },
      { col: 'priority' },
      { col: 'assigned_user_id' },
      { col: 'due_date' },
    ],
    scope: { kind: 'project', optional: true },
    perms: { view: 'automation.view', create: 'automation.manage_tasks', edit: ['automation.manage_tasks', 'automation.execute_action'], delete: 'automation.manage_tasks' },
    required: ['status'],
  },
  {
    key: 'escalations',
    table: 'escalations',
    path: 'escalations',
    idField: 'id',
    columns: [{ col: 'project_id' }],
    scope: { kind: 'project', optional: true },
    perms: { view: 'automation.view', create: ['automation.manage_tasks', 'issues.escalate'], edit: ['automation.manage_tasks', 'automation.execute_action', 'issues.escalate'], delete: null },
  },
  {
    key: 'approvals',
    table: 'approvals',
    path: 'approvals',
    idField: 'id',
    columns: [
      { col: 'project_id' },
      { col: 'approval_type' },
      { col: 'related_entity_type' },
      { col: 'related_entity_id' },
      { col: 'requested_by_id' },
      { col: 'decision' },
      { col: 'decision_by_id' },
      { col: 'decision_at', from: 'decision_date', kind: 'ts' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'approvals.view', create: 'approvals.request', edit: ['approvals.request', 'approvals.decide', 'variations.client_approve'], delete: null },
    required: ['project_id', 'approval_type', 'decision'],
    hooks: approvalHooks,
  },
  {
    key: 'variations',
    table: 'variations',
    path: 'variations',
    idField: 'id',
    columns: [
      { col: 'project_id' },
      { col: 'variation_number' },
      { col: 'status' },
      { col: 'estimated_cost', from: num('estimated_cost'), kind: 'num' },
      { col: 'client_amount', from: num('client_amount'), kind: 'num' },
      { col: 'approved_at', kind: 'ts' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'variations.view', create: 'variations.create', edit: ['variations.create', 'variations.approve', 'variations.client_approve'], delete: null },
    required: ['project_id', 'variation_number', 'status'],
    hooks: variationHooks,
  },
  {
    key: 'clientChangeRequests',
    table: 'client_change_requests',
    path: 'client-change-requests',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'work_item_id' }, { col: 'linked_variation_id' }, { col: 'status' }],
    scope: { kind: 'project' },
    perms: { view: 'variations.view', create: ['variations.create', 'variations.client_approve'], edit: ['variations.create', 'variations.approve', 'variations.client_approve'], delete: null },
    required: ['project_id'],
  },
  {
    key: 'qcRecords',
    table: 'qc_records',
    path: 'qc-records',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'work_item_id' }, { col: 'result' }],
    scope: { kind: 'project' },
    perms: { view: 'work_items.view', create: 'work_items.qc', edit: 'work_items.qc', delete: null },
    required: ['project_id', 'work_item_id'],
  },
  {
    key: 'siteMeasurements',
    table: 'site_measurements',
    path: 'site-measurements',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'work_item_id' }],
    scope: { kind: 'project' },
    perms: { view: 'installation.view', create: ['installation.update', 'work_items.edit'], edit: ['installation.update', 'work_items.edit'], delete: null },
    required: ['project_id'],
  },

  // ---------------- Production ----------------
  {
    key: 'productionOrders',
    table: 'production_orders',
    path: 'production-orders',
    idField: 'id',
    columns: [
      { col: 'project_id' },
      { col: 'work_package_id' },
      { col: 'work_item_id' },
      { col: 'contractor_id' },
      { col: 'status' },
      { col: 'client_drawing_revision_id' },
      { col: 'nw_drawing_revision_id' },
      { col: 'drawing_check', from: (r) => r.drawing_check ?? 'valid' },
      { col: 'drawing_check_reason' },
      { col: 'production_method' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'production.view', create: 'production.create_orders', edit: ['production.update', 'production.create_orders'], delete: null },
    required: ['project_id', 'work_package_id', 'work_item_id', 'status'],
    hooks: productionOrderHooks,
  },
  ...(
    [
      ['productionParts', 'production_parts', 'production-parts', [{ col: 'work_item_id' }, { col: 'part_code' }, { col: 'status' }, { col: 'barcode' }], ['production.update', 'production.cnc_manage']],
      ['cncJobs', 'cnc_jobs', 'cnc-jobs', [{ col: 'status' }], ['production.cnc_manage', 'production.update']],
      ['assemblyJobs', 'assembly_jobs', 'assembly-jobs', [{ col: 'status' }], ['production.update']],
      ['finishingJobs', 'finishing_jobs', 'finishing-jobs', [{ col: 'status' }], ['production.update']],
      ['factoryQCInspections', 'factory_qc_inspections', 'factory-qc', [{ col: 'result' }], ['production.update']],
      ['packingPackages', 'packing_packages', 'packing-packages', [{ col: 'status' }, { col: 'barcode' }], ['production.update']],
      ['productionIssues', 'production_issues', 'production-issues', [{ col: 'status' }], ['production.update', 'issues.create']],
    ] as const
  ).map(
    ([key, table, path, columns, edit]): ModuleDef => ({
      key,
      table,
      path,
      idField: 'id',
      columns: [{ col: 'production_order_id' }, ...columns],
      scope: { kind: 'order' },
      perms: { view: 'production.view', create: [...edit], edit: [...edit], delete: null },
      required: ['production_order_id'],
    })
  ),
  {
    key: 'cncFileVersions',
    table: 'cnc_file_versions',
    path: 'cnc-file-versions',
    idField: 'id',
    columns: [{ col: 'part_code' }, { col: 'revision' }, { col: 'status' }],
    scope: { kind: 'company' },
    perms: { view: 'production.view', create: 'production.cnc_manage', edit: 'production.cnc_manage', delete: null },
  },
  {
    key: 'productionMaterials',
    table: 'production_materials',
    path: 'production-materials',
    idField: 'id',
    columns: [],
    scope: { kind: 'company' },
    perms: { view: 'production.view', create: ['production.update', 'purchasing.create'], edit: ['production.update', 'purchasing.create'], delete: null },
  },

  // ---------------- Delivery & site ----------------
  {
    key: 'deliveryRecords',
    table: 'deliveries',
    path: 'deliveries',
    idField: 'id',
    columns: [
      { col: 'project_id' },
      { col: 'work_package_id' },
      { col: 'contractor_id' },
      { col: 'arranged_by', from: (r) => r.arranged_by ?? 'Contractor' },
      { col: 'status' },
      { col: 'delivery_date' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'delivery.view', create: 'delivery.schedule', edit: ['delivery.schedule', 'delivery.load', 'delivery.receive'], delete: null },
    required: ['project_id', 'status'],
    hooks: deliveryHooks,
  },
  {
    key: 'deliveryReceipts',
    table: 'delivery_receipts',
    path: 'delivery-receipts',
    idField: 'id',
    columns: [{ col: 'delivery_id' }, { col: 'project_id' }],
    scope: { kind: 'project' },
    perms: { view: 'delivery.view', create: null, edit: null, delete: null },
    readOnly: true,
    orderBy: 'recorded_at',
  },
  {
    key: 'installationJobs',
    table: 'installation_jobs',
    path: 'installation-jobs',
    idField: 'id',
    columns: [
      { col: 'project_id' },
      { col: 'work_package_id' },
      { col: 'work_item_id' },
      { col: 'contractor_id' },
      { col: 'supervisor_id', from: 'site_supervisor_id' },
      { col: 'status' },
      { col: 'drawing_revision_id' },
      { col: 'production_order_id' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'installation.view', create: 'installation.update', edit: ['installation.update', 'installation.qc'], delete: null },
    required: ['project_id', 'work_item_id', 'status'],
    hooks: installationHooks,
  },
  {
    key: 'siteQCInspections',
    table: 'site_qc_inspections',
    path: 'site-qc',
    idField: 'id',
    columns: [
      { col: 'project_id' },
      { col: 'work_item_id' },
      { col: 'installation_job_id' },
      { col: 'result' },
      { col: 'inspected_at', from: 'inspection_date' },
      { col: 'rectification_issue_id' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'installation.view', create: 'installation.qc', edit: 'installation.qc', delete: null },
    required: ['project_id', 'work_item_id', 'result'],
    hooks: siteQcHooks,
  },
  {
    key: 'handoverRecords',
    table: 'handover_records',
    path: 'handovers',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'client_id' }, { col: 'status' }],
    scope: { kind: 'project' },
    perms: { view: ['handover.manage', 'projects.view'], create: 'handover.manage', edit: 'handover.manage', delete: null },
    required: ['project_id'],
  },

  // ---------------- Commercial ----------------
  {
    key: 'clientEnquiries',
    table: 'client_enquiries',
    path: 'client-enquiries',
    idField: 'id',
    columns: [{ col: 'client_id' }, { col: 'status' }],
    scope: { kind: 'client' },
    perms: { view: 'commercial.view', create: 'commercial.edit', edit: 'commercial.edit', delete: null },
    required: ['client_id'],
  },
  {
    key: 'commercialTenders',
    table: 'commercial_tenders',
    path: 'tenders',
    idField: 'id',
    columns: [{ col: 'client_id' }, { col: 'enquiry_id' }, { col: 'status' }],
    scope: { kind: 'client' },
    perms: { view: 'commercial.view', create: 'commercial.edit', edit: 'commercial.edit', delete: null },
    required: ['client_id'],
  },
  {
    key: 'commercialQuotations',
    table: 'commercial_quotations',
    path: 'quotations',
    idField: 'id',
    columns: [
      { col: 'client_id' },
      { col: 'project_id' },
      { col: 'status' },
      { col: 'total_selling_price', from: num('total_selling_price'), kind: 'num' },
      { col: 'total_estimated_cost', from: num('total_estimated_cost'), kind: 'num' },
    ],
    scope: { kind: 'client' },
    perms: { view: 'commercial.view', create: 'commercial.edit', edit: 'commercial.edit', delete: null },
    required: ['client_id', 'status'],
  },
  {
    key: 'priceDatabase',
    table: 'price_database',
    path: 'price-database',
    idField: 'id',
    columns: [],
    scope: { kind: 'company' },
    perms: { view: 'commercial.costing', create: 'commercial.costing', edit: 'commercial.costing', delete: null },
  },
  {
    key: 'commercialBaselines',
    table: 'commercial_baselines',
    path: 'commercial-baselines',
    idField: 'project_id',
    columns: [
      { col: 'project_id' },
      { col: 'original_contract_value', from: num('original_contract_value'), kind: 'num' },
      { col: 'original_budget_direct_cost', from: num('original_budget_direct_cost'), kind: 'num' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'commercial.view', create: 'commercial.edit', edit: ['commercial.edit', 'finance.edit'], delete: null },
    required: ['project_id'],
    // Totals (committed, actual, forecast, gross profit...) are computed by the server.
    hooks: baselineHooks,
  },
  {
    key: 'suppliers',
    table: 'suppliers',
    path: 'suppliers',
    idField: 'id',
    columns: [],
    scope: { kind: 'company' },
    perms: { view: 'purchasing.view', create: 'purchasing.manage_suppliers', edit: 'purchasing.manage_suppliers', delete: null },
  },
  {
    key: 'purchaseOrders',
    table: 'purchase_orders',
    path: 'purchase-orders',
    idField: 'id',
    columns: [
      { col: 'project_id' },
      { col: 'supplier_id' },
      { col: 'status' },
      { col: 'total_amount', from: num('total_amount'), kind: 'num' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'purchasing.view', create: 'purchasing.create', edit: ['purchasing.manage_pos', 'purchasing.create'], delete: null },
    required: ['project_id', 'status'],
  },
  {
    key: 'goodsReceived',
    table: 'goods_received',
    path: 'goods-received',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'po_id' }, { col: 'supplier_id' }],
    scope: { kind: 'project' },
    perms: { view: 'purchasing.view', create: ['purchasing.manage_pos', 'delivery.receive'], edit: 'purchasing.manage_pos', delete: null },
    required: ['project_id'],
  },
  {
    key: 'materialRequests',
    table: 'material_requests',
    path: 'material-requests',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'status' }],
    scope: { kind: 'project' },
    perms: { view: 'purchasing.view', create: ['purchasing.create', 'work_items.edit'], edit: ['purchasing.manage_pos', 'purchasing.create'], delete: null },
    required: ['project_id'],
  },
  {
    key: 'projectCostLedger',
    table: 'project_cost_ledger',
    path: 'cost-ledger',
    idField: 'cost_id',
    columns: [
      { col: 'project_id' },
      { col: 'work_package_id' },
      { col: 'work_item_id' },
      { col: 'status' },
      { col: 'amount', from: num('amount'), kind: 'num' },
    ],
    scope: { kind: 'project' },
    perms: { view: 'commercial.view', create: ['commercial.edit', 'finance.edit'], edit: ['commercial.edit', 'finance.edit'], delete: null },
    required: ['project_id', 'status'],
  },
  {
    key: 'commercialInvoices',
    table: 'commercial_invoices',
    path: 'invoices',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'status' }],
    scope: { kind: 'project' },
    perms: { view: 'finance.view', create: ['finance.edit', 'commercial.edit'], edit: ['finance.edit', 'finance.record_payments'], delete: null },
    required: ['project_id'],
  },
  {
    key: 'costLeakAlerts',
    table: 'cost_leak_alerts',
    path: 'cost-leak-alerts',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'status' }],
    scope: { kind: 'project' },
    perms: { view: 'commercial.view', create: 'commercial.edit', edit: 'commercial.edit', delete: null },
    required: ['project_id'],
  },
  {
    key: 'cashflowEntries',
    table: 'cashflow_entries',
    path: 'cashflow',
    idField: 'id',
    columns: [{ col: 'project_id' }],
    scope: { kind: 'project' },
    perms: { view: 'finance.view', create: 'finance.edit', edit: 'finance.edit', delete: null },
    required: ['project_id'],
  },
  {
    key: 'financialClaims',
    table: 'financial_claims',
    path: 'claims',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'status' }],
    scope: { kind: 'project' },
    perms: { view: 'finance.view', create: 'finance.manage_claims', edit: 'finance.manage_claims', delete: null },
    required: ['project_id'],
  },
  {
    key: 'payments',
    table: 'payments',
    path: 'payments',
    idField: 'id',
    columns: [{ col: 'project_id' }, { col: 'status' }],
    scope: { kind: 'project' },
    perms: { view: 'finance.view', create: 'finance.record_payments', edit: 'finance.record_payments', delete: null },
    required: ['project_id'],
  },
];

export const MODULE_BY_KEY = new Map(MODULES.map((m) => [m.key, m]));
export const MODULE_BY_PATH = new Map(MODULES.map((m) => [m.path, m]));
